import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ToastContainer } from "react-toastify";
import { ThemeProvider } from "next-themes";
import StoreProvider from "./StoreProvider";
 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
      
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <body>
            <div className="container mx-auto px-4">
              <Navbar />
              {children}
              <ToastContainer />
            </div>
          </body>
        </ThemeProvider>
      </StoreProvider>
    </html>
  );
}
